### ISSUE TITLE
Are you aware of decimer.ai?

### ISSUE THREAD

**Issue by OBrink** [Ixorlive/ChemRec#1]
Hey @Ixorlive,

This is an interesting project, but we are wondering if you are aware of the official DECIMER.ai web service hosted on https://decimer.ai (source code and documentation available [here](https://github.com/OBrink/DECIMER.ai)).

I don't want to stop you from developing your own user interface, but we have already implemented a web application for this exact purpose. Maybe have a look at it. We are always happy about criticism and contributions! :)

Kind regards,
Otto

**Comment by Ixorlive** [comment]
Hello, Otto. I was surprised to see here)
Thank you for your attention and for your comment about decimer.ai.

Of course I know about your project, I have studied in detail all your projects within DECIMER. You can convince yourself of this, because i have given a link to your site [here](https://github.com/Ixorlive/ChemRec/blob/3884ca3f54da438208ba3a0f7558aa1c6fee05bc/web/src/components/About/About.tsx#L17) =)

I'm sorry to bother you with this. This is an ordinary student project to study your model and try to use and integrate it into various services yourself. I will, of course, close the repository soon (I just wanted to share the code with my supervisor).

Once again, I apologize for my invention of the wheel, it's just part of the tutorial, nothing more :)

Best regards

**Comment by OBrink** [comment]
Hey @Ixorlive,

Please don't apologise! You are not bothering anyone! I just became aware of this project as GitHub lists it as a repository that uses DECIMER. I think this is a cool project and just wanted to make sure that you don't put a lot of effort into something to then realise later that it has already been implemented elsewhere! :)

Have a nice day! 
Otto
